#!/usr/bin/env bash
# OpenClaw 场景收集脚本
# 每天自动收集 OpenClaw 可落地场景并生成 HTML 报告

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
REPORTS_DIR="$PROJECT_ROOT/reports"
DAILY_DIR="$PROJECT_ROOT/daily-logs"
DATE=$(date '+%Y-%m-%d')
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

echo "🦞 OpenClaw 场景收集 - $DATE"
echo "================================"

# 确保目录存在
mkdir -p "$REPORTS_DIR" "$DAILY_DIR"

# 搜索关键词列表
KEYWORDS=(
  "OpenClaw 实际应用场景"
  "OpenClaw use cases"
  "OpenClaw 工作流 workflow"
  "OpenClaw 自动化场景"
  "OpenClaw AI agent 用例"
)

# 存储搜索结果
RESULTS_FILE="$DAILY_DIR/$DATE-raw.json"
HTML_FILE="$REPORTS_DIR/index.html"
DAILY_HTML="$DAILY_DIR/$DATE.html"

echo "📊 搜索场景信息..."

# 初始化 JSON 数组
echo '{"date": "'$DATE'", "timestamp": "'$TIMESTAMP'", "scenarios": []}' > "$RESULTS_FILE"

# 遍历关键词搜索
for keyword in "${KEYWORDS[@]}"; do
  echo "  搜索：$keyword"
  
  # 调用 mcporter 搜索
  SEARCH_RESULT=$(mcporter call "博查搜索.web_search" query:"$keyword" count:10 summary:true 2>&1 || echo '{"error": "search failed"}')
  
  # 简单处理结果（实际应该用 jq 解析）
  if [[ "$SEARCH_RESULT" == *"webPages"* ]]; then
    echo "    ✓ 找到结果"
  else
    echo "    ✗ 无结果"
  fi
done

echo ""
echo "📝 生成 HTML 报告..."

# 生成 HTML
cat > "$HTML_FILE" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OpenClaw 可落地场景日报</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      padding: 40px 20px;
    }
    .container {
      max-width: 1400px;
      margin: 0 auto;
    }
    .header {
      background: rgba(255,255,255,0.95);
      padding: 40px;
      border-radius: 20px;
      margin-bottom: 30px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
    }
    .header h1 {
      font-size: 36px;
      color: #667eea;
      margin-bottom: 10px;
    }
    .header .subtitle {
      font-size: 16px;
      color: #666;
    }
    .header .meta {
      margin-top: 20px;
      display: flex;
      gap: 20px;
      flex-wrap: wrap;
    }
    .header .meta-item {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: #fff;
      padding: 8px 16px;
      border-radius: 20px;
      font-size: 14px;
    }
    .scenario-card {
      background: rgba(255,255,255,0.95);
      border-radius: 20px;
      padding: 30px;
      margin-bottom: 20px;
      box-shadow: 0 10px 40px rgba(0,0,0,0.2);
      transition: transform 0.2s;
    }
    .scenario-card:hover {
      transform: translateY(-5px);
    }
    .scenario-card h2 {
      color: #667eea;
      font-size: 24px;
      margin-bottom: 15px;
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .scenario-card .meta {
      display: flex;
      gap: 15px;
      flex-wrap: wrap;
      margin-bottom: 20px;
    }
    .scenario-card .tag {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: #fff;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 12px;
    }
    .scenario-card .source {
      color: #666;
      font-size: 14px;
    }
    .scenario-card .summary {
      line-height: 1.8;
      color: #333;
      font-size: 15px;
    }
    .scenario-card .url {
      display: inline-block;
      margin-top: 15px;
      color: #667eea;
      text-decoration: none;
      font-weight: 500;
    }
    .scenario-card .url:hover {
      text-decoration: underline;
    }
    .footer {
      text-align: center;
      color: rgba(255,255,255,0.8);
      margin-top: 40px;
      font-size: 14px;
    }
    .loading {
      text-align: center;
      padding: 60px;
      color: #fff;
      font-size: 18px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🦞 OpenClaw 可落地场景日报</h1>
      <div class="subtitle">每天自动收集 OpenClaw 实际应用案例和工作流</div>
      <div class="meta">
        <span class="meta-item">📅 更新日期：{{DATE}}</span>
        <span class="meta-item">🔍 场景数量：{{COUNT}}</span>
        <span class="meta-item">⏰ 更新时间：{{TIME}}</span>
      </div>
    </div>

    <div class="scenarios">
      {{SCENARIOS}}
    </div>

    <div class="footer">
      <p>Generated by OpenClaw Auto Collector • 数据来源于博查搜索</p>
      <p>最后更新：{{DATE}} {{TIME}}</p>
    </div>
  </div>
</body>
</html>
HTMLEOF

echo "✅ 报告生成完成：$HTML_FILE"
echo ""
echo "📂 文件位置:"
echo "   HTML 报告：$HTML_FILE"
echo "   原始数据：$RESULTS_FILE"
echo ""
